#!/usr/bin/env python3
"""
cert2carray.py  —  createcert.py で生成した CA 証明書を
                   penquic (CERT_VERIFY=ON) が読み取れる形式に変換する

出力形式:
  1. ca_cert.der        — DER バイナリ (openssl verify 等で使う)
  2. ca_cert_der.c      — PC/Linux ビルド向け C 配列
  3. ca_cert_der_pico.c — PicoW ビルド向け C 配列 (flash 配置)

使い方:
  python cert2carray.py                        # デフォルト: ca_cert.crt を変換
  python cert2carray.py ca_cert.crt            # ファイルを指定
  python cert2carray.py ca_cert.crt --out-dir ./certs
  python cert2carray.py --var-name my_ca_cert  # C 変数名を変更
  python cert2carray.py --verify               # 変換後に openssl で検証
"""

import argparse, sys
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec


class CACert2DER:
    """
# PEM 形式の CA 証明書を DER に変換し、プラットフォーム別の C 配列ソースを生成するクラス  

* pemPath     : CA 証明書 PEM ファイルのパス                  
* outDir      : 出力先ディレクトリ (デフォルト: カレント)     
* varName     : 生成する C 変数名 (デフォルト: ca_cert_der)   
    """
    def __init__(
        self,
        pemPath : Path | str,
        outDir  : Path | str = ".",
        varName : str        = "ca_cert_der",
    ):
        self.pemPath = Path(pemPath)
        self.outDir  = Path(outDir)
        self.varName = varName
        self._der: bytes | None = None   # 変換後の DER キャッシュ



    def pem2der(self) -> bytes:
        """# PEM を読み込んで DER バイト列を返す"""
        try:
            with open(self.pemPath, "rb") as f:
                pemData = f.read()
        except OSError as e:
            sys.exit(f"[ERROR] ファイルを開けませんでした: {e}")

        try:
            cert = x509.load_pem_x509_certificate(pemData)
        except Exception as e:
            sys.exit(f"[ERROR] PEM 証明書の読み込みに失敗しました: {e}")

        self._der = cert.public_bytes(serialization.Encoding.DER)
        return self._der


    def check_cert_requirements(self) -> int:
        """
        # penquic との互換性を検証し、エラーを表示  
        # エラー件数を返す。0 なら互換。
        """
        error = 0

        with open(self.pemPath, "rb") as f:
            cert = x509.load_pem_x509_certificate(f.read())

        # 1. 署名アルゴリズム: ecdsa-with-SHA256 のみサポート
        algo = cert.signature_algorithm_oid.dotted_string
        # OID 1.2.840.10045.4.3.2 = ecdsa-with-SHA256
        if algo != "1.2.840.10045.4.3.2":
            print(f"""署名アルゴリズムが ecdsa-with-SHA256 ではありません (OID: {algo})。
penquic は ecdsa_secp256r1_sha256 のみサポートします。""")
            error += 1

        # 2. 公開鍵: EC P-256 (secp256r1) のみ
        pub = cert.public_key()
        if not isinstance(pub, ec.EllipticCurvePublicKey):
            print("公開鍵が EC 鍵ではありません。penquic は EC P-256 のみサポートします。")
            error += 1
        elif not isinstance(pub.curve, ec.SECP256R1):
            print(f"""EC 曲線が secp256r1 ではありません ({pub.curve.name})。
penquic は secp256r1 のみサポートします。""")
            error += 1

        # 3. CA フラグ: BasicConstraints の CA:TRUE
        try:
            bc = cert.extensions.get_extension_for_class(x509.BasicConstraints)
            if not bc.value.ca:
                print("""BasicConstraints の CA フラグが FALSE です。
Root CA 証明書を指定してください (サーバ証明書は不可)。""")
                error += 1
        except x509.ExtensionNotFound:
            print("""BasicConstraints 拡張がありません。
Root CA 証明書を指定してください。""")
            error += 1

        return error

    def _der_to_c_array(self, der: bytes, forPico: bool = False) -> str:
        """
        # DER バイト列を C 配列ソースコードに変換する。

        - forPico=True の場合は PicoW (RP2040) 向けに
        __attribute__((aligned(4))) と flash 配置用の属性を付ける。
        """
        hexLines = []
        for i in range(0, len(der), 16):
            chunk = der[i:i + 16]
            hexLines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
        hexBody = ",\n".join(hexLines)

        if forPico:
            # PicoW: フラッシュに配置して RAM を消費しない
            arrayDecl = f"""
const uint8_t 
    __attribute__((section(".rodata"))) 
    __attribute__((aligned(4)))
    {self.varName}[]"""
            lenDecl = f"const size_t {self.varName}_len = sizeof({self.varName});"
            header = """#include <stdint.h>
#include <stddef.h>"""
        else:
            # PC / Linux: unsigned char + unsigned int (xxd -i 互換)
            arrayDecl = f"unsigned char {self.varName}[]"
            lenDecl = f"unsigned int {self.varName}_len = {len(der)};"
            header = f"""/* generated by cert2carray.py */
/* usage:
 *   #include "ca_cert_der.c"
 *   params.ca_cert_der     = {self.varName};
 *   params.ca_cert_der_len = {self.varName}_len;
 */"""

        return f"""\
{header}

{arrayDecl} = {{
{hexBody}
}};
{lenDecl}
"""

    def write_files(self, dryRun: bool = False) -> dict[str, Path]:
        """
        # DER バイナリと 2 種類の C ファイルを outDir に書き出す
        - 生成パスの辞書を返す
        """
        der = self._der if self._der is not None else self.pem2der()

        self.outDir.mkdir(parents=True, exist_ok=True)

        outputs = {
            "der":  self.outDir / "ca_cert.der",
            "c_pc": self.outDir / "ca_cert_der.c",
            "c_pi": self.outDir / "ca_cert_der_pico.c",
        }

        if dryRun:
            print("[DRY RUN] 以下のファイルを生成します:")
            for p in outputs.values():
                print(f"  {p}")
            return outputs

        with open(outputs["der"], "wb") as f:
            f.write(der)

        with open(outputs["c_pc"], "w", encoding="utf-8") as f:
            f.write(self._der_to_c_array(der, forPico=False))

        with open(outputs["c_pi"], "w", encoding="utf-8") as f:
            f.write(self._der_to_c_array(der, forPico=True))

        return outputs


    def verify_der(self, derPath: Path) -> None:
        """
        #  openssl を使った後検証 (オプション)
        - openssl x509 で DER ファイルを読んで内容を表示する
        """
        import subprocess
        result = subprocess.run(
            ["openssl", "x509", "-in", str(derPath), "-inform", "DER",
             "-text", "-noout"],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            print(f"[WARN] openssl verify failed: {result.stderr.strip()}")
        else:
            # 重要行だけ抜き出して表示
            important = [
                line for line in result.stdout.splitlines()
                if any(kw in line for kw in (
                    "Subject:", "Issuer:", "Not Before", "Not After",
                    "CA:", "Public Key Algorithm", "NIST CURVE", "Signature Algorithm"
                ))
            ]
            print("\n[DER 検証 (openssl x509)]")
            for line in important:
                print(" ", line.strip())


# ──────────────────────────────────────────────
#  エントリポイント
# ──────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="createcert.py 生成の CA 証明書を penquic 用 C 配列に変換します"
    )
    parser.add_argument(
        "pem",
        nargs="?",
        default="ca_cert.crt",
        help="CA 証明書 PEM ファイル (デフォルト: ca_cert.crt)",
    )
    parser.add_argument(
        "--out-dir",
        default=".",
        metavar="DIR",
        help="出力ディレクトリ (デフォルト: カレント)",
    )
    parser.add_argument(
        "--var-name",
        default="ca_cert_der",
        metavar="NAME",
        help="C 変数名 (デフォルト: ca_cert_der)",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="変換後に openssl x509 で DER を検証して内容を表示する",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="ファイルを書き出さずに何が生成されるかだけ表示する",
    )
    args = parser.parse_args()

    # argparse は --out-dir / --var-name / --dry-run のハイフンを
    # アンダースコアに変換するため、ここでキャメルケース変数に受け直す
    pemPath  = Path(args.pem)
    outDir   = args.out_dir
    varName  = args.var_name
    dryRun   = args.dry_run
    doVerify = args.verify

    # ── 入力チェック ──
    if not pemPath.exists():
        sys.exit(f"[ERROR] ファイルが見つかりません: {pemPath}")

    converter = CACert2DER(
        pemPath = pemPath,
        outDir  = outDir,
        varName = varName,
    )

    print(f"""\
入力  : {pemPath}
出力先: {outDir}/""")

    # ── 要件チェック ──
    warnings = converter.check_cert_requirements()
    if warnings > 0:
        print("\n[WARN] penquic との互換性に問題があります:")
        sys.exit(warnings)
    else:
        print("[OK]  EC P-256 / ecdsa-with-SHA256 — penquic 互換")

    # ── 変換 ──
    der = converter.pem2der()
    print(f"DER サイズ: {len(der)} bytes")

    outputs = converter.write_files(dryRun=dryRun)

    if not dryRun:
        print(f"""
生成ファイル:
  {outputs['der']}          — DER バイナリ
  {outputs['c_pc']}    — PC/Linux ビルド用 C 配列
  {outputs['c_pi']} — PicoW ビルド用 C 配列 (flash 配置)

使い方 (PC/Linux):
  #include "{outputs['c_pc'].name}"
  params.ca_cert_der     = {varName};
  params.ca_cert_der_len = {varName}_len;

使い方 (PicoW):
  #include "{outputs['c_pi'].name}"
  params.ca_cert_der     = {varName};
  params.ca_cert_der_len = {varName}_len;"""
        )

        if doVerify:
            converter.verify_der(outputs["der"])
